AWSTemplateFormatVersion: 2010-09-09
Description: Serverless Djando in Lambda Container

Parameters:
  DeploymentBucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: DeploymentBucketName
  DeploymentEcrArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: DeploymentEcrArn
  DeploymentEcrUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: DeploymentEcrUri

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${DeploymentBucketName}/infrastructure/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.180.0.0/16
        PublicSubnet1CIDR: 10.180.8.0/21
        PublicSubnet2CIDR: 10.180.16.0/21
        PrivateSubnet1CIDR: 10.180.24.0/21
        PrivateSubnet2CIDR: 10.180.32.0/21

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${DeploymentBucketName}/infrastructure/security-groups.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${DeploymentBucketName}/infrastructure/rds.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.RdsSecurityGroup

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${DeploymentBucketName}/infrastructure/api.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        DeploymentEcrUri: !Ref DeploymentEcrUri
        DeploymentEcrArn: !Ref DeploymentEcrArn
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.LambdaSecurityGroup